name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  determine-affected-service:
    runs-on: ubuntu-latest
    outputs:
      service: ${{ steps.check-service.outputs.service }}
    steps:
      - uses: actions/checkout@v4
      - id: check-service
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" == feature:auth_service/* ]]; then
            echo "service=auth_service" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.pull_request.head.ref }}" == feature:appointment_service/* ]]; then
            echo "service=appointment_service" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.pull_request.head.ref }}" == feature:availability_service/* ]]; then
            echo "service=availability_service" >> $GITHUB_OUTPUT
          else
            echo "service=all" >> $GITHUB_OUTPUT
          fi

  test-and-build:
    needs: determine-affected-service
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth_service, appointment_service, availability_service]
    if: needs.determine-affected-service.outputs.service == 'all' || needs.determine-affected-service.outputs.service == matrix.service
    steps:
      - uses: actions/checkout@v4

      - name: Run tests for ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          make unit-tests

      - name: Build Docker image for ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          docker build -t ${DOCKER_USERNAME}/fiap-health-${{ matrix.service }}:${{ github.sha }} -f Dockerfile .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        run: docker push ${DOCKER_USERNAME}/fiap-health-${{ matrix.service }}:${{ github.sha }}

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
